# Generated by Django 4.1 on 2025-09-19 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AcuerdoOperativa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numerador', models.IntegerField()),
                ('tipo_unidad', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('unidad_parada', models.BooleanField(default=False)),
                ('fecha_limite', models.DateField()),
                ('pendiente', models.BooleanField(default=True)),
                ('responsable', models.CharField(max_length=100)),
                ('porcentaje_avance', models.PositiveIntegerField()),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'acuerdos_operativa',
                'ordering': ['numerador'],
            },
        ),
        migrations.CreateModel(
            name='Integrante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'integrantes_operativo',
            },
        ),
    ]
