# Generated by Django 4.1 on 2025-09-22 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operativo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='acuerdooperativa',
            name='responsable_manual',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
